### ISSUE TITLE
데브툴즈 유발, 톰캣... 버전이슈로 추정되는 WrongThreadException

### ISSUE THREAD

**Issue by parksangdonews** [parksangdonews/booksbooksbooks#5]
* 에러원인(추청):  
  데브툴즈 유발, 톰캣... 버전이슈로 추정되는 WrongThreadException
* 로그
  ```
  2023-06-11 13:38:00.965 DEBUG 5779 --- [  restartedMain] o.apache.tomcat.util.compat.Jre19Compat  : Class not found so assuming code is running on a pre-Java 19 JVM

  java.lang.ClassNotFoundException: java.lang.WrongThreadException
  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
    중략
  	at com.parksangdo.booksbooks.BooksbooksApplication.main(BooksbooksApplication.java:10) ~[main/:na]
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
  	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.7.13-SNAPSHOT.jar:2.7.13-SNAPSHOT]

**Comment by MinseongNa** [comment]
> * 에러원인(추청):
>   데브툴즈 유발, 톰캣... 버전이슈로 추정되는 WrongThreadException

* 에러원인
  * 에러가 아닌 톰캣의 자바버전 체크 로직의 로그 출력.
  * 관련코드  
    ```
    org.apache.tomcat.util.compat.Jre19Compat.java
      
    static {
      // Don't need any Java 19 specific classes (yet) so just test for one of
      // the new ones for now.
      Class<?> c1 = null;
      try {
        c1 = Class.forName("java.lang.WrongThreadException");
      } catch (ClassNotFoundException cnfe) {
        // Must be pre-Java 16
        log.debug(sm.getString("jre19Compat.javaPre19"), cnfe);
      }

      supported = (c1 != null);
    }
    ```

* 해결방법
  * 자바버전을 19이상으로 올림.
    * Exception이 로그에 표시되어 익셉션으로 혼동하기 쉬우나,  
      자바 버전을 체크하기위해 WrongThreadException을 선택한 것이므로 에러는 아님
      * 톰캣에서 `ClassNotFoundException cnfe`를 로그에 안남기는 게 베스트라고 생각됨.
    * 자바버전을 올려도 나중에 더 최신버전이 나왔을 때 발생할 이슈

* 대응내용
  * 대응필요없음
